### ISSUE TITLE
Flaky mobileAppYC Jest suite: one random test fails per full parallel run

### ISSUE THREAD

**Issue by ankit-yc** [YosemiteCrew/Yosemite-Crew#1822]
**Describe the bug**

The `apps/mobileAppYC` Jest suite has a systemic test-isolation flake. A full parallel run (`pnpm --filter mobileAppYC exec jest --ci --maxWorkers=2`) intermittently fails ONE random test that passes when run in isolation. This reddens the "CI for affected workspaces (mobileAppYC)" and "SonarQube Analysis - mobile" jobs on every mobile PR.

Root cause: three pre-existing tests build component trees with react-test-renderer's `renderer.create(...)` but never await their async mount work or unmount the tree. React Native Testing Library auto-cleanup only unmounts trees created via `render()`, so these leak - the async work resolves after the test finishes and commits deferred React updates into whichever suite runs next on the same worker (maxWorkers=2). The deferred commit throws (for example `window.dispatchEvent is not a function` from react-test-renderer's global error path) and jest-circus attributes it to the currently-running sibling test, a different one each run.

Leaking tests:

- `__tests__/App.test.tsx` - `<App />`'s startup effect (mobile-config fetch via axios, AsyncStorage reads, reducer dispatches, PersistGate rehydration) resolves after the test ends.
- `__tests__/screens/PlaceholderScreens.snapshot.test.tsx` - screen mount work renders after the Jest environment is torn down.
- `__tests__/screens/EmptyScreens.snapshot.test.tsx` - renders `GenericEmptyScreen` without a redux Provider, so `useTheme` -> `useAppDispatch` throws and the error leaks asynchronously (the stored snapshots were all `null`).

**To Reproduce**

1. Check out a clean `dev`.
2. Run `pnpm --filter mobileAppYC exec jest --ci --maxWorkers=2`.
3. Repeat a few times.
4. See a different random test fail per run, each passing in isolation, alongside "Cannot log after tests are done" warnings and uncaught `window.dispatchEvent is not a function` errors traced back to `App.tsx` and the two snapshot suites.

**Expected behavior**

The full parallel suite passes deterministically on every run, with no post-teardown log or error leaks bleeding across test files.

**Screenshots**

N/A (CI / local test-runner output).

**Desktop (please complete the following information):**

N/A - test infrastructure. Reproduced locally and in CI on the `mobileAppYC` workspace (Jest 29, react-test-renderer 19, RN 0.81, `--maxWorkers=2`).

**Smartphone (please complete the following information):**

N/A - the flake is in the Jest test environment, not on a device.

**Additional context**

Fix: drain each leaking test's pending async work inside `act()` and unmount the tree before the test finishes (mock `fetchMobileConfig` for deterministic startup in App.test.tsx; add a redux Provider in EmptyScreens.snapshot.test.tsx). No `jest.retryTimes` - the root async leak is fixed.

Validated on a clean `origin/dev` checkout: pre-fix reproduced the flake; post-fix ran the full suite green 5 times in a row (6274 tests, 424 suites) with zero post-teardown leaks.

**Comment by ankit-yc** [comment]
Fixed on dev by #1821 (commit 5db7f3141), which fixed the react-test-renderer teardown leaks that were flaking the suite. Closing as resolved.
